# Generated by Django 5.1.6 on 2025-04-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=280)),
                ('image', models.ImageField(upload_to='movie/images/')),
                ('prompt', models.CharField(max_length=280)),
            ],
        ),
    ]
